FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_DJANGO_API_URL
ARG VITE_FASTAPI_URL
ARG VITE_STREAM_URL

ENV VITE_DJANGO_API_URL=$VITE_DJANGO_API_URL
ENV VITE_FASTAPI_URL=$VITE_FASTAPI_URL
ENV VITE_STREAM_URL=$VITE_STREAM_URL

COPY frontend/package*.json ./

RUN npm ci

COPY frontend .

RUN npm run build


FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]